# Generated by Django 5.2.6 on 2025-09-27 16:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=30, verbose_name="نام")),
                ("last_name", models.CharField(max_length=30)),
                (
                    "national_code",
                    models.CharField(db_index=True, max_length=10, unique=True),
                ),
                ("birth_date", models.DateTimeField()),
                ("home_address", models.CharField(max_length=200)),
                (
                    "postal_code",
                    models.CharField(db_index=True, max_length=10, unique=True),
                ),
                ("register_date", models.DateTimeField()),
                ("phone_number", models.CharField(max_length=11, unique=True)),
                ("education", models.CharField(max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
