# Generated by Django 5.2.6 on 2025-09-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="first_name",
            field=models.CharField(max_length=30, verbose_name="نام"),
        ),
    ]
